// <auto-generated />
namespace CarRenting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class empnoreq : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(empnoreq));
        
        string IMigrationMetadata.Id
        {
            get { return "202012291737473_emp-no-req"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
